Repository kamg2218/pingpong, pull requests merged in 2022-03, with the labels that each got.

#44 🎉 update main branch
  frontend/.env
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/SideMenuChat.tsx
  frontend/src/components/games/MenuGame.tsx
  frontend/src/components/modals/MyProfileModal.tsx
  frontend/src/components/modals/ProfileModal.tsx
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Play.tsx
  frontend/src/pages/games/SideMenuGame.tsx
  frontend/src/pages/games/WaitingRoom.tsx
  frontend/src/pages/login/NickAndProfile.tsx
  frontend/src/pages/login/Qrcode.tsx
Labels: bug

#51 🧪 test main page
  backend/docker-compose.yml
  frontend/src/App.tsx
  frontend/src/components/chat/ChatBox.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/MenuChat.tsx
  frontend/src/components/chat/MenuChatDropdown.tsx
  frontend/src/components/chat/MyChatBox.tsx
  frontend/src/components/chat/PublicChatList.tsx
  frontend/src/components/chat/SideMenuChat.tsx
  frontend/src/components/games/MenuGame.tsx
  frontend/src/components/modals/InputPwdModal.tsx
  frontend/src/components/modals/MuteModal.css
  frontend/src/components/modals/MuteModal.tsx
  frontend/src/components/modals/MyProfileModal.tsx
  frontend/src/css/ChatRoom.css
  frontend/src/pages/Main.tsx
  frontend/src/pages/login/NickAndProfile.tsx
Labels: bug

#56 🎨 arrange page design
  frontend/.env
  frontend/.gitignore
  frontend/src/components/chat/ChatBox.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/MenuChat.tsx
  frontend/src/components/chat/MenuChatBox.tsx
  frontend/src/components/chat/chat.css
  frontend/src/components/games/GameBox.tsx
  frontend/src/components/games/GameRoomSlide.css
  frontend/src/components/games/GameRoomSlide.tsx
  frontend/src/components/games/MatchHistory.tsx
  frontend/src/components/games/MenuGame.css
  frontend/src/components/games/MenuGame.tsx
  frontend/src/components/modals/MyProfileModal.tsx
  frontend/src/components/play/MenuPlay.css
  frontend/src/components/play/MenuPlay.tsx
  frontend/src/components/play/PlayRoom.tsx
  frontend/src/css/MenuGame.css
  frontend/src/pages/Main.css
  frontend/src/pages/Main.tsx
  frontend/src/pages/games/Game.css
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Lobby.tsx
  frontend/src/pages/games/Play.css
  frontend/src/pages/games/Play.tsx
  frontend/src/pages/games/SideMenuGame.tsx
  frontend/src/pages/games/SideMenuPlay.tsx
  frontend/src/pages/games/WaitingRoom.tsx
  frontend/src/pages/games/waitingRoom.css
  frontend/src/pages/login/Qrcode.tsx
  frontend/src/socket/userSocket.tsx
Labels: enhancement

#59 🐛 fix: qrcode error
  frontend/src/components/modals/MyProfileModal.tsx
  frontend/src/components/play/PlayRoom.tsx
  frontend/src/pages/games/Game.css
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/WaitingRoom.tsx
  frontend/src/pages/login/Qrcode.tsx
Labels: bug

#62 🔥 add Redux
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/chat/ChatBox.tsx
  frontend/src/components/chat/ChatRoom.css
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/InviteList.tsx
  frontend/src/components/chat/MenuChat.tsx
  frontend/src/components/chat/MenuChatBox.tsx
  frontend/src/components/chat/MenuChatDropdown.tsx
  frontend/src/components/chat/MyChatBox.tsx
  frontend/src/components/chat/PublicChatList.tsx
  frontend/src/components/chat/SideMenuChat.tsx
  frontend/src/components/chat/TitleInput.tsx
  frontend/src/components/games/GameBox.tsx
  frontend/src/components/games/GameRoomSlide.tsx
  frontend/src/components/games/MatchHistory.tsx
  frontend/src/components/games/MenuGame.tsx
  frontend/src/components/modals/AddChatModal.tsx
  frontend/src/components/modals/AddGameRoomModal.tsx
  frontend/src/components/modals/CheckModal.tsx
  frontend/src/components/modals/InputPwdModal.tsx
  frontend/src/components/modals/InviteModal.tsx
  frontend/src/components/modals/MatchRequestModal.tsx
  frontend/src/components/modals/MuteModal.tsx
  frontend/src/components/modals/MyProfileModal.tsx
  frontend/src/components/modals/ProfileModal.tsx
  frontend/src/components/modals/PublicChatModal.tsx
  frontend/src/components/modals/PwdModal.tsx
  frontend/src/components/play/MenuPlay.tsx
  frontend/src/components/play/PlayRoom.tsx
  frontend/src/index.tsx
  frontend/src/pages/Main.tsx
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Lobby.tsx
  frontend/src/pages/games/Play.tsx
  frontend/src/pages/games/SideMenuGame.tsx
  frontend/src/pages/games/SideMenuPlay.tsx
  frontend/src/pages/games/WaitingRoom.tsx
  frontend/src/pages/login/NickAndProfile.tsx
  frontend/src/pages/login/Qrcode.tsx
  frontend/src/redux/chatReducer.tsx
  frontend/src/redux/gameReducer.tsx
  frontend/src/redux/rootReducer.tsx
  frontend/src/redux/userReducer.tsx
  frontend/src/socket/socket.tsx
  frontend/src/types/chatTypes.tsx
  frontend/src/types/gameTypes.tsx
  frontend/src/types/userTypes.tsx
Labels: enhancement

#64 🐛 fix: input error and gameRoomList state
  frontend/src/components/games/GameRoomSlide.tsx
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Lobby.tsx
  frontend/src/pages/games/WaitingRoom.tsx
  frontend/src/redux/gameReducer.tsx
Labels: bug

#65 🐛 fix: input tag in twofactor page
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/play/MenuPlay.tsx
  frontend/src/pages/Main.tsx
  frontend/src/pages/games/Lobby.tsx
  frontend/src/pages/games/WaitingRoom.tsx
  frontend/src/pages/login/Qrcode.tsx
  frontend/src/pages/login/qrcode.css
Labels: bug

#69 🩹 fix: update main branch
  frontend/src/components/chat/ChatBox.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/MenuChat.tsx
  frontend/src/components/chat/MenuChatBox.tsx
  frontend/src/components/chat/MenuChatDropdown.tsx
  frontend/src/components/chat/MyChatBox.tsx
  frontend/src/components/chat/SideMenuChat.tsx
  frontend/src/components/games/MenuGame.tsx
  frontend/src/components/play/MenuPlay.tsx
  frontend/src/pages/Main.tsx
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/WaitingRoom.tsx
  frontend/src/pages/games/waitingRoom.css
  frontend/src/types/chatTypes.tsx
  frontend/src/types/urlTypes.tsx
Labels: bug

#70 fix : typo in changeGameRoom
  backend/src/db/entity/Chat/ChatRoom.entity.ts
  backend/src/socketEvents/game/gameElement/game.ts
  backend/src/socketEvents/game/gameGateway.service.ts
Labels: bug

#72 🚀 update main branch
  frontend/src/components/modals/ProfileModal.tsx
  frontend/src/pages/games/WaitingRoom.tsx
Labels: bug

#74 fix : draw event
  backend/src/socketEvents/game/gameElement/game.ts
Labels: bug

#76 ✅ update ProfileModal and MyProfileModal
  frontend/src/components/games/MenuGame.tsx
  frontend/src/components/modals/MyProfileModal.tsx
  frontend/src/components/modals/ProfileModal.tsx
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/SideMenuGame.tsx
  frontend/src/pages/games/WaitingRoom.tsx
Labels: bug, enhancement
