Repository kamg2218/pingpong, pull requests merged in 2022-04, with the labels that each got.

#77 🧪 test chat and addFriend sockets
  backend/src/.env
  frontend/src/components/chat/ChatBox.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/MenuChat.tsx
  frontend/src/components/chat/MyChatBox.tsx
  frontend/src/components/chat/SideMenuChat.tsx
  frontend/src/components/games/MenuGame.css
  frontend/src/components/play/PlayRoom.tsx
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Play.tsx
  frontend/src/pages/games/SideMenuGame.tsx
Labels: bug

#79 ✅ update states
  backend/src/.env
  frontend/src/components/chat/ChatBox.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/InviteList.tsx
  frontend/src/components/chat/MenuChat.tsx
  frontend/src/components/chat/MyChatBox.tsx
  frontend/src/components/chat/SideMenuChat.tsx
  frontend/src/components/chat/chat.css
  frontend/src/components/games/MenuGame.tsx
  frontend/src/components/modals/MyProfileModal.tsx
  frontend/src/components/modals/ProfileModal.tsx
  frontend/src/components/modals/PublicChatModal.tsx
  frontend/src/components/play/MenuPlay.tsx
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/SideMenuGame.tsx
  frontend/src/pages/games/WaitingRoom.tsx
  frontend/src/socket/socket.tsx
  frontend/src/types/urlTypes.tsx
Labels: dependencies

#84 ✨ add manager modal and update loading modal
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/MenuChat.tsx
  frontend/src/components/chat/MenuChatBox.tsx
  frontend/src/components/chat/MenuChatDropdown.tsx
  frontend/src/components/chat/PublicChatList.tsx
  frontend/src/components/chat/SideMenuChat.tsx
  frontend/src/components/chat/TitleInput.tsx
  frontend/src/components/chat/chat.css
  frontend/src/components/modals/AddChatModal.css
  frontend/src/components/modals/InputPwdModal.tsx
  frontend/src/components/modals/InviteModal.tsx
  frontend/src/components/modals/LoadingModal.tsx
  frontend/src/components/modals/ManagerModal.tsx
  frontend/src/components/modals/MatchRequestModal.tsx
  frontend/src/components/modals/ProfileModal.tsx
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Lobby.tsx
  frontend/src/types/chatTypes.tsx
  frontend/src/types/urlTypes.tsx
Labels: enhancement

#87 🐛 update mute modal and socket off
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/InviteList.tsx
  frontend/src/components/chat/MenuChat.tsx
  frontend/src/components/chat/MenuChatDropdown.tsx
  frontend/src/components/chat/SideMenuChat.tsx
  frontend/src/components/games/GameBox.tsx
  frontend/src/components/games/GameRoomSlide.tsx
  frontend/src/components/games/MenuGame.tsx
  frontend/src/components/modals/AddChatModal.css
  frontend/src/components/modals/InputPwdModal.tsx
  frontend/src/components/modals/InviteModal.tsx
  frontend/src/components/modals/ManagerModal.tsx
  frontend/src/components/modals/MuteModal.tsx
  frontend/src/components/modals/MyProfileModal.tsx
  frontend/src/components/modals/PwdModal.tsx
  frontend/src/components/play/MenuPlay.tsx
  frontend/src/components/play/PlayRoom.tsx
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Lobby.tsx
  frontend/src/pages/games/SideMenuGame.tsx
Labels: bug

#88 🐛 update mute modal and manager modal
  frontend/src/components/modals/ManagerList.tsx
  frontend/src/components/modals/ManagerModal.tsx
  frontend/src/components/modals/MuteList.tsx
  frontend/src/components/modals/MuteModal.tsx
Labels: bug

#90 ✏️ fix props clearly
  frontend/src/components/chat/ChatBox.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/MenuChat.tsx
  frontend/src/components/chat/MenuChatBox.tsx
  frontend/src/components/chat/MenuChatDropdown.tsx
  frontend/src/components/chat/MyChatBox.tsx
  frontend/src/components/chat/PublicChatList.tsx
  frontend/src/components/chat/SideMenuChat.tsx
  frontend/src/components/chat/TitleInput.tsx
  frontend/src/components/games/GameBox.tsx
  frontend/src/components/games/GameRoomSlide.tsx
  frontend/src/components/games/MatchHistory.tsx
  frontend/src/components/games/MenuGame.tsx
  frontend/src/components/login/ProfileCarousel.tsx
  frontend/src/components/modals/AddChatModal.tsx
  frontend/src/components/modals/AddGameRoomModal.tsx
  frontend/src/components/modals/AlertModal.tsx
  frontend/src/components/modals/CheckModal.tsx
  frontend/src/components/modals/InputPwdModal.tsx
  frontend/src/components/modals/InviteList.tsx
  frontend/src/components/modals/InviteModal.tsx
  frontend/src/components/modals/LoadingModal.tsx
  frontend/src/components/modals/ManagerList.tsx
  frontend/src/components/modals/ManagerModal.tsx
  frontend/src/components/modals/MatchRequestModal.tsx
  frontend/src/components/modals/MuteList.tsx
  frontend/src/components/modals/MuteModal.tsx
  frontend/src/components/modals/MyProfileModal.tsx
  frontend/src/components/modals/ProfileModal.tsx
  frontend/src/components/modals/PublicChatModal.tsx
  frontend/src/components/modals/PwdModal.tsx
  frontend/src/pages/Main.tsx
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Lobby.tsx
  frontend/src/pages/games/SideMenuGame.tsx
  frontend/src/pages/games/SideMenuPlay.tsx
  frontend/src/pages/games/WaitingRoom.tsx
  frontend/src/pages/login/NickAndProfile.tsx
  frontend/src/pages/login/Qrcode.tsx
  frontend/src/socket/socket.tsx
  frontend/src/types/chatTypes.tsx
  frontend/src/types/gameTypes.tsx
  frontend/src/types/urlTypes.tsx
Labels: bug, enhancement

#91 Fix : match response error, delete room error
  backend/src/db/entity/User/User.entity.ts
  backend/src/db/repository/Chat/ChatHistoryRepository.ts
  backend/src/db/repository/Game/GameMembership.repository.ts
  backend/src/socketEvents/auth/auth.gateway.ts
  backend/src/socketEvents/chat/chat.gateway.ts
  backend/src/socketEvents/game/game.gateway.ts
  backend/src/socketEvents/game/gameElement/game.ts
  backend/src/socketEvents/game/gameGateway.service.ts
  backend/src/socketEvents/user/user.gateway.ts
  backend/src/socketEvents/user/userGateway.service.ts
Labels: bug

#92 🎨 update page design
  frontend/src/components/play/PlayRoom.tsx
  frontend/src/components/play/playRoom.css
  frontend/src/pages/games/Game.css
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Play.css
  frontend/src/pages/games/Play.tsx
  frontend/src/pages/games/SideMenuPlay.tsx
  frontend/src/types/urlTypes.tsx
Labels: enhancement

#94 🐛 update chatMessage socket in chatRoom
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/types/chatTypes.tsx
Labels: bug

#97 ✅ update design
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/games/GameBox.tsx
  frontend/src/components/games/GameRoomSlide.tsx
  frontend/src/components/games/MatchHistory.tsx
  frontend/src/components/modals/AddChatModal.css
  frontend/src/components/modals/AddGameRoomModal.tsx
  frontend/src/components/modals/Modals.css
  frontend/src/components/modals/MuteModal.tsx
  frontend/src/components/modals/MyProfileModal.tsx
  frontend/src/components/modals/profileModal.css
  frontend/src/types/gameTypes.tsx
Labels: bug, enhancement

#98 ✅ update design and carousel items
  frontend/src/components/games/GameRoomSlide.tsx
  frontend/src/components/modals/LoadingModal.tsx
  frontend/src/components/modals/Modals.css
  frontend/src/components/modals/MyProfileModal.tsx
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Lobby.tsx
  frontend/src/pages/games/waitingRoom.css
Labels: bug, documentation, enhancement

#99 ✅ update exitGameRoom in waitingRoom
  frontend/src/pages/games/WaitingRoom.tsx
Labels: bug

#105 🐛 update changeGameRoom
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/WaitingRoom.tsx
Labels: bug

#113 🐛 update user check api
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Lobby.tsx
  frontend/src/pages/games/Play.tsx
  frontend/src/pages/games/WaitingRoom.tsx
Labels: bug

#120 📝 update quotes and semicolons
  frontend/.env
  frontend/src/App.tsx
  frontend/src/components/chat/ChatBox.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/MenuChat.tsx
  frontend/src/components/chat/MenuChatBox.tsx
  frontend/src/components/chat/MenuChatDropdown.tsx
  frontend/src/components/chat/MyChatBox.tsx
  frontend/src/components/chat/PublicChatList.tsx
  frontend/src/components/chat/SideMenuChat.tsx
  frontend/src/components/chat/TitleInput.tsx
  frontend/src/components/games/GameBox.tsx
  frontend/src/components/games/GameRoomSlide.tsx
  frontend/src/components/games/MatchHistory.tsx
  frontend/src/components/games/MenuGame.tsx
  frontend/src/components/login/ProfileCarousel.css
  frontend/src/components/login/ProfileCarousel.tsx
  frontend/src/components/modals/AddChatModal.tsx
  frontend/src/components/modals/AddGameRoomModal.tsx
  frontend/src/components/modals/AlertModal.tsx
  frontend/src/components/modals/CheckModal.tsx
  frontend/src/components/modals/InputPwdModal.tsx
  frontend/src/components/modals/InviteList.tsx
  frontend/src/components/modals/InviteModal.tsx
  frontend/src/components/modals/LoadingModal.tsx
  frontend/src/components/modals/ManagerList.tsx
  frontend/src/components/modals/ManagerModal.tsx
  frontend/src/components/modals/MatchRequestModal.tsx
  frontend/src/components/modals/MuteList.tsx
  frontend/src/components/modals/MuteModal.tsx
  frontend/src/components/modals/MyProfileModal.tsx
  frontend/src/components/modals/ProfileModal.tsx
  frontend/src/components/modals/PublicChatModal.tsx
  frontend/src/components/modals/PwdModal.tsx
  frontend/src/components/play/MenuPlay.tsx
  frontend/src/components/play/ObserverProfileBox.tsx
  frontend/src/components/play/PlayRoom.tsx
  frontend/src/css/ChatRoom.css
  frontend/src/css/Game.css
  frontend/src/css/index.css
  frontend/src/icons/Profile.tsx
  frontend/src/index.tsx
  frontend/src/pages/Main.css
  frontend/src/pages/Main.tsx
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Lobby.tsx
  frontend/src/pages/games/Play.tsx
  frontend/src/pages/games/SideMenuGame.tsx
  frontend/src/pages/games/SideMenuPlay.tsx
  frontend/src/pages/games/WaitingRoom.tsx
  frontend/src/pages/login/NickAndProfile.tsx
  frontend/src/pages/login/Qrcode.tsx
  frontend/src/redux/chatReducer.tsx
  frontend/src/redux/gameReducer.tsx
  frontend/src/redux/rootReducer.tsx
  frontend/src/redux/userReducer.tsx
  frontend/src/socket/chatSocket.tsx
  frontend/src/socket/socket.tsx
  frontend/src/socket/userSocket.tsx
Labels: documentation

#122 🏗️ add disabled conditions for match request in profile modal
  frontend/src/components/modals/ProfileModal.tsx
  frontend/src/index.tsx
Labels: enhancement

#123 📝 remove console logs
  backend/src/.env
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/MenuChat.tsx
  frontend/src/components/chat/MenuChatBox.tsx
  frontend/src/components/chat/SideMenuChat.tsx
  frontend/src/components/chat/TitleInput.tsx
  frontend/src/components/games/GameRoomSlide.tsx
  frontend/src/components/games/MenuGame.tsx
  frontend/src/components/modals/MuteModal.tsx
  frontend/src/components/modals/MyProfileModal.tsx
  frontend/src/components/modals/ProfileModal.tsx
  frontend/src/components/modals/PublicChatModal.tsx
  frontend/src/components/play/MenuPlay.tsx
  frontend/src/components/play/PlayRoom.tsx
  frontend/src/pages/Main.tsx
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Lobby.tsx
  frontend/src/pages/games/Play.tsx
  frontend/src/pages/games/SideMenuGame.tsx
  frontend/src/pages/games/SideMenuPlay.tsx
  frontend/src/pages/games/WaitingRoom.tsx
  frontend/src/pages/login/NickAndProfile.tsx
  frontend/src/pages/login/Qrcode.tsx
  frontend/src/socket/socket.tsx
Labels: documentation

#125 📝 update chat url in chatroom
  frontend/src/components/chat/ChatRoom.tsx
Labels: bug

#126 🐛 update chat box menu dropdown modals
  frontend/src/components/chat/MenuChat.tsx
  frontend/src/components/chat/MenuChatBox.tsx
  frontend/src/components/chat/MenuChatDropdown.tsx
  frontend/src/components/modals/AddChatModal.tsx
  frontend/src/components/modals/InputPwdModal.tsx
  frontend/src/components/modals/InviteList.tsx
  frontend/src/components/modals/ManagerModal.tsx
  frontend/src/components/modals/MatchRequestModal.tsx
  frontend/src/types/urlTypes.tsx
Labels: bug

#127 🏗️ create enterPlayRoom api and update user api
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/pages/games/Lobby.tsx
  frontend/src/pages/games/Play.tsx
  frontend/src/pages/games/WaitingRoom.tsx
  frontend/src/types/gameTypes.tsx
Labels: bug, enhancement

#129 🏗️ update user check api in waitingroom
  frontend/src/pages/games/WaitingRoom.tsx
  frontend/src/types/urlTypes.tsx
Labels: bug

#130 🐛 update gameReducer error
  frontend/src/components/play/PlayRoom.tsx
  frontend/src/css/.index.css.icloud
  frontend/src/pages/Main.tsx
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Play.tsx
  frontend/src/redux/chatReducer.tsx
  frontend/src/redux/gameReducer.tsx
Labels: bug

#131 🏗️ create requestLogout api
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Play.tsx
  frontend/src/pages/login/NickAndProfile.tsx
  frontend/src/pages/login/Qrcode.tsx
Labels: documentation

#132 🏗️ create requestLogout api
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Play.tsx
  frontend/src/pages/login/NickAndProfile.tsx
  frontend/src/pages/login/Qrcode.tsx
Labels: enhancement

#133 🐛 update requestLogout api
  frontend/src/components/play/PlayRoom.tsx
  frontend/src/pages/games/Game.tsx
  frontend/src/pages/games/Lobby.tsx
  frontend/src/pages/games/Play.tsx
  frontend/src/pages/games/WaitingRoom.tsx
  frontend/src/pages/login/Qrcode.tsx
Labels: bug, enhancement

#134 🏗️ update socket apis
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/modals/AddGameRoomModal.tsx
  frontend/src/components/modals/profileModal.css
  frontend/src/components/play/MenuPlay.tsx
  frontend/src/pages/games/Lobby.tsx
  frontend/src/pages/games/WaitingRoom.tsx
Labels: bug, enhancement

#135 🗑️ delete nickname login
  frontend/src/pages/Main.tsx
Labels: documentation

#136 ✅ update handleExit in menu play
  frontend/src/components/play/MenuPlay.tsx
Labels: enhancement
